#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Supports: Linux

inetd_list () {
	pattern="${1}"
	cat /etc/inetd.conf | grep -v "^#" | grep -v "^$" | grep "${pattern}" | while read portnumber _ _ _ _ _ _ _
	do
		printf "${portnumber}\n"
	done
}

inetd_show_command () {
	portnumber="${1}"
	cat /etc/inetd.conf | grep "^${portnumber}" | while read _ _ _ _ _ command _ _
	do
		printf "${command}\n"
	done
}

inetd_show_userid () {
	portnumber="${1}"
	cat /etc/inetd.conf | grep "^${portnumber}" | while read _ _ _ _ userid _ _ _
	do
		printf "${userid}\n"
	done
}

inetd_show_arguments () {
	portnumber="${1}"
	cat /etc/inetd.conf | grep "^${portnumber}" | while read _ _ _ _ _ _ arguments _
	do
		printf "${arguments}\n"
	done
}
