#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Supports: Linux

process_list () {
	pattern="${1}"
	ps -aeo ruser,rgroup,pid,ppid,args | grep -v "PID" | grep "${pattern}" | grep -v "grep" | while read _ _ processid _ _ _
	do
		printf "${processid}\n"
	done
}

process_show_command () {
	pid="${1}"
	ps -aeo pid,args | grep -v "PID" | grep "${pid} " | grep -v "grep" | while read processid cmd _
	do
		printf "${cmd}\n"
	done
}

process_show_userid () {
	pid="${1}"
	ps -aeo ruser,pid | grep -v "PID" | grep "${pid} " | grep -v "grep" | while read userid processid
	do
		printf "${userid}\n"
	done
}

process_show_parentid () {
	pid="${1}"
	ps -aeo pid,ppid | grep -v "PID" | grep "${pid} " | grep -v "grep" | while read processid parentid
	do
		printf "${parentid}\n"
	done
}
