#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Supports: Linux

if [ -z "${groupincluded}" ]
then

groupincluded=1

. lib/misc/validate
. lib/misc/passwd

user_is_trusted () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	# TODO write this
	false
}

user_is_root () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	if [ -n "`groups \"${username}\" | egrep -- \"root\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

user_is_in_group_id () {
	username="${1}"
	groupid="${2}"
	[ "`validate_is_string \"${username}\"`" ] || false
	[ "`validate_is_number \"${groupid}\"`" ] || false
	# TODO write this
	false
}

user_is_in_group_name () {
	username="${1}"
	group="${2}"
	[ "`validate_is_string \"${username}\"`" ] || false
	[ "`validate_is_string \"${group}\"`" ] || false
	if [ -n "`groups \"${username}\" | egrep -- \"${group}\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

user_is_user_id () {
	userid="${1}"
	[ "`validate_is_number \"${userid}\"`" ] || false
	if [ -n "`user_show_user_id | egrep -- \"^${userid}$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

user_is_user_name () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	if [ -n "`id -u -n | egrep -- \"^${username}$\"`" ]
	then
		printf -- "1\n"
	else
		printf -- "0\n"
	fi
}

user_show_user_id () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -u`\n"
}

user_show_user_name () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -u -n`\n"
}

user_show_group_id () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -g`\n"
}

user_show_group_ids () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -G`\n"
}

user_show_group_name () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -g -n`\n"
}

user_show_group_names () {
	username="${1}"
	[ "`validate_is_string \"${username}\"`" ] || false
	printf -- "`id -G -n`\n"
}

user_match_user_name () {
	pattern="${1}"
	[ "`validate_is_string \"${pattern}\"`" ] || false
	passwd_list | while read username
	do
		if [ -n "`printf -- \"${username}\" | egrep -- \"${pattern}\"`" ]
		then
			printf -- "${username}\n"
		fi
	done
}

fi
