#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# List group-writable files

. lib/misc/stdio
. lib/misc/file

group_writable_init () {
	stdio_message_log "group_writable" "Starting"
}

group_writable_permissions () {
	pattern="${1}"
	file_show_nonsymlink_perms " ${pattern}$" | while read filename permissions userid groupid
	do
		case "${permissions}" in
			?????w????)
				if [ -n "`id -G -n | grep ${groupid}`" ]
				then
					stdio_message_warn "group_writable" "${filename} is owned by user ${userid} (group ${groupid}: YOU) and is group-writable (${permissions})"
				else
					stdio_message_log "group_writable" "${filename} is owned by user ${userid} (group ${groupid}) and is group-writable (${permissions})"
				fi
			;;
		esac
	done
}

group_writable_main () {
	file_list_by_perm "^.....w.... " | while read filename dummy dummy dummy dummy
	do
		if [ -h "${filename}" ]
		then
			linkedfilename="`file_show_symlinked_file "${filename}"`"

			if [ -e "${linkedfilename}" ]
			then
				#stdio_message_debug "group_writable" "${filename} is a symlink to ${linkedfilename}"
				group_writable_permissions "${linkedfilename}"
			fi
		elif [ -e "${filename}" ]
		then
			group_writable_permissions "${filename}"
		fi
	done
}

group_writable_fini () {
	stdio_message_log "group_writable" "Ending"
}
