#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# List users with no password set

. lib/misc/stdio
. lib/misc/shadow

shadow_hashes_init () {
	stdio_message_log "shadow_hashes" "Starting"
}

shadow_hashes_main () {
	shadow_list ".*" | while read username
	do
		hash="`shadow_show_hash "${username}"`"
		if [ -z "${hash}" ]
		then
			stdio_message_warn "shadow_hashes" "${username} has no password set"
		fi
	done
}

shadow_hashes_fini () {
	stdio_message_log "shadow_hashes" "Ending"
}
