#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check for write permissions over privileged files and processes'
# linked libraries

. lib/misc/stdio
. lib/misc/file
. lib/misc/privileged
. lib/misc/linker

binary_dependency_init () {
	stdio_message_log "binary_dependency" "Starting: `date`"
}

binary_dependency_permissions () {
	library="${1}"
	privfilename="${2}"
	filetype="${3}"
	echo "library beginning: $library (privfilename: $privfilename)"
	file_show_non_symlink_perms " ${library}$" | while read filename permissions userid groupid
	do
		echo "filename: ${filename}"
		case "${permissions}" in
			????????w?)
				stdio_message_warn "binary_dependency" "${filetype} ${privfilename} depends on ${filename}, owned by user ${userid} (group ${groupid}) and is world-writable (${permissions})"
			;;
			?????w????)
				if [ -n "`id -G -n | grep ${groupid}`" ]
				then
					stdio_message_warn "binary_dependency" "${filetype} ${privfilename} depends on ${filename}, owned by user ${userid} (group ${groupid}: YOU) and is group-writable (${permissions})"
				else
					stdio_message_log "binary_dependency" "${filetype} ${privfilename} depends on ${filename}, owned by user ${userid} (group ${groupid}) and is group-writable (${permissions})"
				fi
			;;
		esac
	done
}

binary_dependency_main () {
	privileged_list | while read filetype filename usergroupid
	do
		linker_list_dependencies "${filename}" | while read library
		do
			if [ ! -e "${library}" ]
			then
				stdio_message_warn "binary_dependency" "${filetype} ${filename} depends on ${library}, but this does not exist"
				continue
			fi

			if [ -h "${library}" ]
			then
				linkedlibrary="`file_show_symlinked_filename "${library}"`"

				if [ -n "${linkedlibrary}" ]
				then
					#stdio_message_debug "binary_dependency" "${filetype} ${filename} depends on ${library}, a symlink to ${linkedlibrary}"
					binary_dependency_permissions "${linkedlibrary}" "${filename}" "${filetype}"
				fi
			else
				binary_dependency_permissions "${library}" "${filename}" "${filetype}"
			fi
		done
	done
}

binary_dependency_fini () {
	stdio_message_log "binary_dependency" "Ending: `date`"
}
