#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# Check for writable permissions on system configuration files and directories

. lib/misc/file
. lib/misc/group
. lib/misc/permission
. lib/misc/stdio

system_configuration_init () {
	stdio_message_log "system_configuration" "Starting at: `date`"
}

system_configuration_main () {
	sensitive_config_files="/etc/passwd /etc/group /etc/master.passwd /etc/init.d /etc/inittab /etc/inetd.conf /etc/xinetd.conf /etc/crontab /etc/cron.d /etc/cron.daily /etc/cron.weekly /etc/cron.monthly /etc/fstab /etc/profile /etc/sudoers /etc/hosts.equiv /etc/shosts.equiv"
	file_show_non_symlink_perms " /etc" | while read filename permissions userid groupid
	do
		sensitive="0"
		if [ -n "`printf -- \"${sensitive_config_files}\" | egrep -- \"${filename}\"`" ]
		then
			sensitive="1"
		fi
		if [ "${sensitive}" -eq 1 ]
		then
			message="- sensitive file"
		else
			message=""
		fi
		case "${permissions}" in
			????????w?)
				if [ "`permission_is_world_writable_sticky_bit \"${permissions}\"`" -eq 1 ]
				then
					stdio_message_log "system_configuration" "${filename} is owned by user ${userid} (group ${groupid}) and is world-writable with sticky bit (${permissions})"
				else
					stdio_message_warn "system_configuration" "${filename} is owned by user ${userid} (group ${groupid}) and is world-writable (${permissions})${message}"
				fi
				;;
			?????w????)
				if [ "`group_is_in_group_name \"${groupid}\"`" -eq 1 ]
				then
					stdio_message_warn "system_configuration" "${filename} is owned by user ${userid} (group ${groupid}: YOU) and is group-writable (${permissions})${message}"
				else
					stdio_message_debug "system_configuration" "${filename} is owned by user ${userid} (group ${groupid}) and is group-writable (${permissions})"
				fi
				;;
		esac
	done
}

system_configuration_fini () {
	stdio_message_log "system_configuration" "Ending at: `date`"
}
