#!/bin/sh
# $Revision$
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
#
# (c) Tim Brown, 2012
# <mailto:timb@nth-dimension.org.uk>
# <http://www.nth-dimension.org.uk/> / <http://www.machine.org.uk/>
#
# List world-writable files

. lib/misc/stdio
. lib/misc/file

world_writable_init () {
	stdio_message_log "world_writable" "Starting"
	file_check_or_generate_cache
}

world_writable_permissions () {
	pattern="${1}"
	file_show_non_symlink_perms " ${pattern}$" | while read filename permissions userid groupid
	do
		case "${permissions}" in
			????????w?)
				stdio_message_warn "world_writable" "${filename} is owned by user ${userid} (group ${groupid}) and is world-writable (${permissions})"
			;;
		esac
	done
}

world_writable_main () {
	file_list_by_perm "^........w. " | while read filename
	do
		if [ -h "${filename}" ]
		then
			linkedfilename="`file_show_symlinked_filename "${filename}"`"

			if [ -e "${linkedfilename}" ]
			then
				#stdio_message_debug "group_writable" "${filename} is a symlink to ${linkedfilename}"
				world_writable_permissions "${linkedfilename}"
			fi
		elif [ -e "${filename}" ]
		then
			world_writable_permissions "${filename}"
		fi
	done
}

world_writable_fini () {
	stdio_message_log "world_writable" "Ending"
}
